apiVersion: v1
kind: Namespace
metadata:
  name: quelpoke-florian

---
apiVersion: v1
kind: Service
metadata:
  name: quelpoke-florian-service
  namespace: quelpoke-florian
spec:
  selector:
    app: quelpoke-florian  # Doit correspondre au label du Deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quelpoke-florian
  namespace: quelpoke-florian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quelpoke-florian  # Correspond au selector du Service
  template:
    metadata:
      labels:
        app: quelpoke-florian
    spec:
      containers:
        - name: quelpoke-florian
          image: europe-west9-docker.pkg.dev/cs-poc-hpzdycpiqjyvinhrczvlwcn/student-florian/quelpoke:latest
          ports:
            - containerPort: 8080
          resources: 
            limits:
              memory: "256Mi"
              cpu: "200m"

---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: quelpoke-florian-gateway
  namespace: quelpoke-florian
spec:
  parentRefs:
    - kind: Gateway
      name: external-http-gateway
      namespace: infra
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /florian
      backendRefs:
      - kind: Service
        name: quelpoke-florian-service
        namespace: quelpoke-florian
        port: 8080
