apiVersion: v1
kind: Namespace
metadata:
  name: quelpoke-florian

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quelpoke-florian
  namespace: quelpoke-florian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quelpoke-florian
  template:
    metadata:
      labels:
        app: quelpoke-florian
    spec:
      containers:
        - name: quelpoke-florian
          image: europe-west9-docker.pkg.dev/cs-poc-hpzdycpiqjyvinhrczvlwcn/student-florian/quelpoke:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: HTTPRoute
metadata:
  name: external-http-gateway
  namespace: infra
spec:
  parentRefs:
    - kind: Gateway
      name: external-http-gateway
      namespace: infra
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /florian
      backendRefs:
        - name: quelpoke-florian
          port: 8080
